=== Cray-HPE/csm-redfish-interface-emulator/mockups/XL675d_A100/SchemaStore/en/LogEntry.json/index.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "@odata.id": "LogEntry",
    "additionalProperties": false,
    "copyright": "Copyright 2014-2022 Hewlett Packard Enterprise Development, LP.  Portions Copyright 2014-2019 Distributed Management Task Force. All rights reserved.",
    "description": "This resource defines the record format for a log.  It is designed to be used for SEL logs (from IPMI) as well as Event Logs and OEM-specific log formats.  The EntryType field indicates the type of log and the resource includes several additional properties dependent on the EntryType.",
    "properties": {
        "@odata.context": {
            "$ref": "Resource.json#/definitions/odatacontext"
        },
        "@odata.etag": {
            "$ref": "Resource.json#/definitions/odataetag"
        },
        "@odata.id": {
            "$ref": "Resource.json#/definitions/odataid"
        },
        "@odata.type": {
            "$ref": "Resource.json#/definitions/odatatype"
        },
        "Created": {
            "description": "The date and time when the log entry was created, for example, 2014-04-15T00:38:00Z.",
            "etag": true,
            "format": "date-time",
            "readonly": true,
            "type": "string"
        },
        "EntryType": {
            "description": "The log entry type.",
            "enum": [
                "Oem"
            ],
            "etag": true,
            "readonly": true,
            "type": "string"
        },
        "Id": {
            "$ref": "Resource.json#/definitions/Id"
        },
        "Links": {
            "additionalProperties": false,
            "properties": {
                "OriginOfCondition": {
                    "properties": {
                        "@odata.id": {
                            "$ref": "Resource.json#/definitions/odataid"
                        }
                    },
                    "description": "The link to the resource that caused the log entry.",
                    "readonly": true,
                    "type": "object"
                }
            },
            "description": "The links to other resources that are related to this resource.",
            "readonly": true,
            "type": "object"
        },
        "Message": {
            "description": "The log entry details.",
            "etag": true,
            "readonly": true,
            "type": "string"
        },
        "Name": {
            "$ref": "Resource.json#/definitions/Name"
        },
        "Oem": {
            "additionalProperties": true,
            "properties": {
                "Hpe": {
                    "$ref": "HpeLogEntry.json#",
                    "readonly": false
                }
            },
            "readonly": false,
            "type": "object"
        },
        "OemRecordFormat": {
            "description": "The format of an OEM record.",
            "enum": [
                "Hpe-IML",
                "Hpe-iLOEventLog",
                "Hpe-SL",
                "Hpe-Event"
            ],
            "etag": true,
            "readonly": true,
            "type": "string"
        },
        "Severity": {
            "description": "The log entry severity.",
            "enum": [
                "OK",
                "Warning",
                "Critical"
            ],
            "etag": true,
            "readonly": true,
            "type": "string"
        },
        "EventId": {
            "description": "The unique instance identifier for an event.",
            "etag": true,
            "readonly": true,
            "type": "string"
        },
        "EventTimestamp": {
            "description": "The date and time when the event occurred.",
            "etag": true,
            "format": "date-time",
            "readonly": true,
            "type": "string"
        },
        "MessageArgs": {
            "description": "The arguments for the message.",
            "items": {
                "type": "string"
            },
            "readonly": true,
            "type": "array"
        },
        "MessageId": {
            "description": "The MessageId, event data, or OEM-specific information. This property decodes from the entry type.  If the entry type is `Event`, this property contains a Redfish Specification-defined MessageId.  If the entry type is `SEL`, this property contains the Event Data.  Otherwise, this property contains OEM-specific information.",
            "etag": true,
            "readonly": true,
            "type": "string"
        }
    },
    "readonly": false,
    "title": "#LogEntry.v1_11_0.LogEntry",
    "type": "object"
}

=== Cray-HPE/csm-redfish-interface-emulator/mockups/DL325/Managers/1/LogServices/IEL/Entries/33/index.json
{
    "@odata.context": "/redfish/v1/$metadata#LogEntry.LogEntry",
    "@odata.etag": "W/\"B25971F9\"",
    "@odata.id": "/redfish/v1/Managers/1/LogServices/IEL/Entries/33",
    "@odata.type": "#LogEntry.v1_1_0.LogEntry",
    "Id": "33",
    "Created": "2022-04-14T15:27:15Z",
    "EntryType": "Oem",
    "Message": "Browser login: root - 10.254.1.12(ncn-w002-hmn).",
    "Name": "iLO Event Log",
    "Oem": {
        "Hpe": {
            "@odata.context": "/redfish/v1/$metadata#HpeLogEntry.HpeLogEntry",
            "@odata.type": "#HpeLogEntry.v2_3_0.HpeLogEntry",
            "Categories": [
                "Security",
                "Administration"
            ],
            "Class": 35,
            "ClassDescription": "iLO 5",
            "Code": 1017,
            "Count": 7,
            "EventNumber": 1561508,
            "Severity": "Informational",
            "Updated": "2022-04-14T15:27:52Z"
        }
    },
    "OemRecordFormat": "Hpe-iLOEventLog",
    "Severity": "OK"
}

=== Cray-HPE/csm-redfish-interface-emulator/mockups/XL675d_A40/Systems/1/LogServices/IML/Entries/57/index.json
{
    "@odata.context": "/redfish/v1/$metadata#LogEntry.LogEntry",
    "@odata.etag": "W/\"501C33B3\"",
    "@odata.id": "/redfish/v1/Systems/1/LogServices/IML/Entries/57",
    "@odata.type": "#LogEntry.v1_1_0.LogEntry",
    "Id": "57",
    "Created": "2021-09-01T13:19:35Z",
    "EntryType": "Oem",
    "Message": "At least one of the links is up in adapter HPE Eth 10/25Gb 2p 621SFP28 Adptr in slot 19",
    "Name": "Integrated Management Log",
    "Oem": {
        "Hpe": {
            "@odata.context": "/redfish/v1/$metadata#HpeLogEntry.HpeLogEntry",
            "@odata.type": "#HpeLogEntry.v2_3_0.HpeLogEntry",
            "Categories": [
                "Hardware"
            ],
            "Class": 17,
            "ClassDescription": "Network",
            "Code": 14,
            "Count": 1,
            "EventNumber": 90,
            "Repaired": true,
            "Severity": "Repaired",
            "Updated": "2021-09-02T20:47:13Z"
        }
    },
    "OemRecordFormat": "Hpe-IML",
    "Severity": "OK"
}

=== Cray-HPE/csm-redfish-interface-emulator/mockups/DL325/Systems/1/LogServices/SL/Entries/59/index.json
{
    "@odata.context": "/redfish/v1/$metadata#LogEntry.LogEntry",
    "@odata.etag": "W/\"FBB14FAD\"",
    "@odata.id": "/redfish/v1/Systems/1/LogServices/SL/Entries/59",
    "@odata.type": "#LogEntry.v1_1_0.LogEntry",
    "Id": "59",
    "Created": "2020-09-18T15:02:43Z",
    "EntryType": "Oem",
    "Message": "UNKNOWN EVENT - Class [0xa] and Code [0x277]",
    "Name": "Security Log",
    "Oem": {
        "Hpe": {
            "@odata.context": "/redfish/v1/$metadata#HpeLogEntry.HpeLogEntry",
            "@odata.type": "#HpeLogEntry.v2_3_0.HpeLogEntry",
            "Categories": [
                "Unknown"
            ],
            "Class": 10,
            "ClassDescription": "UEFI",
            "Code": 631,
            "Count": 1,
            "EventNumber": 80,
            "Severity": "Caution",
            "Updated": "2020-09-18T15:02:43Z",
            "UserAction": "None"
        }
    },
    "OemRecordFormat": "Hpe-SL",
    "Severity": "Warning"
}

=== Cray-HPE/csm-redfish-interface-emulator/mockups/XL675d_A40/Systems/1/LogServices/IML/Entries/101/index.json
{
    "@odata.context": "/redfish/v1/$metadata#LogEntry.LogEntry",
    "@odata.etag": "W/\"5940A08C\"",
    "@odata.id": "/redfish/v1/Systems/1/LogServices/IML/Entries/101",
    "@odata.type": "#LogEntry.v1_1_0.LogEntry",
    "Id": "101",
    "Created": "2021-11-18T15:20:40Z",
    "EntryType": "Oem",
    "Message": " All links are down in adapter HPE Eth 10/25Gb 2p 621SFP28 Adptr in slot 19",
    "Name": "Integrated Management Log",
    "Oem": {
        "Hpe": {
            "@odata.context": "/redfish/v1/$metadata#HpeLogEntry.HpeLogEntry",
            "@odata.type": "#HpeLogEntry.v2_3_0.HpeLogEntry",
            "Categories": [
                "Hardware"
            ],
            "Class": 17,
            "ClassDescription": "Network",
            "Code": 13,
            "Count": 1,
            "EventNumber": 134,
            "LearnMoreLink": "http://www.hpe.com/support/class0x0011code0x000d-gen10",
            "RecommendedAction": "Check the connection to the adapter and validate the connectivity from the server to any external device, including the cabling. If no problems are found, the adapter or other connectivity device may need replacement.",
            "Repaired": false,
            "Severity": "Critical",
            "Updated": "2021-11-18T15:20:40Z"
        }
    },
    "OemRecordFormat": "Hpe-IML",
    "Severity": "Critical"
}

=== Cray-HPE/csm-redfish-interface-emulator/mockups/XL675d_A100/Systems/1/LogServices/Event/Entries/5/index.json
{
    "@odata.context": "/redfish/v1/$metadata#LogEntry.LogEntry",
    "@odata.etag": "W/\"89BF5661\"",
    "@odata.id": "/redfish/v1/Systems/1/LogServices/Event/Entries/5/",
    "@odata.type": "#LogEntry.v1_11_0.LogEntry",
    "Id": "5",
    "Created": "2022-06-13T20:19:59Z",
    "EntryType": "Oem",
    "EventId": "10f184ba-8bfc-18d9-282b-dc240e94d5a6",
    "EventTimestamp": "2022-06-13T20:19:59Z",
    "Links": {
        "OriginOfCondition": {
            "@odata.id": "/redfish/v1/Systems/1/"
        }
    },
    "MessageId": "iLOEvents.3.2.ServerResetDetected",
    "Name": "Event",
    "OemRecordFormat": "Hpe-Event",
    "Severity": "Warning"
}

=== Cray-HPE/csm-redfish-interface-emulator/mockups/XL675d_A40/Systems/1/LogServices/SL/Entries/14/index.json
{
    "@odata.context": "/redfish/v1/$metadata#LogEntry.LogEntry",
    "@odata.etag": "W/\"17C114F8\"",
    "@odata.id": "/redfish/v1/Systems/1/LogServices/SL/Entries/14",
    "@odata.type": "#LogEntry.v1_1_0.LogEntry",
    "Id": "14",
    "Created": "2021-07-30T16:06:04Z",
    "EntryType": "Oem",
    "Message": "The overall security state of the system is at \"Risk\".",
    "Name": "Security Log",
    "Oem": {
        "Hpe": {
            "@odata.context": "/redfish/v1/$metadata#HpeLogEntry.HpeLogEntry",
            "@odata.type": "#HpeLogEntry.v2_3_0.HpeLogEntry",
            "Categories": [
                "Security",
                "Administration",
                "Configuration"
            ],
            "Class": 55,
            "ClassDescription": "Security Configuration",
            "Code": 5,
            "Count": 1,
            "EventNumber": 21,
            "RecommendedAction": "Refer to iLO user manual or Security Dashboard help page.",
            "Severity": "Caution",
            "Updated": "2021-07-30T16:06:04Z",
            "UserAction": "None"
        }
    },
    "OemRecordFormat": "Hpe-SL",
    "Severity": "Warning"
}

=== Cray-HPE/csm-redfish-interface-emulator/mockups/XL675d_A40/Systems/1/LogServices/IML/Entries/157/index.json
{
    "@odata.context": "/redfish/v1/$metadata#LogEntry.LogEntry",
    "@odata.etag": "W/\"60309446\"",
    "@odata.id": "/redfish/v1/Systems/1/LogServices/IML/Entries/157",
    "@odata.type": "#LogEntry.v1_1_0.LogEntry",
    "Id": "157",
    "Created": "2022-01-10T22:29:59Z",
    "EntryType": "Oem",
    "Message": "Firmware flashed (Apollo Gen10Plus Chassis CPLD Package 20210201)",
    "Name": "Integrated Management Log",
    "Oem": {
        "Hpe": {
            "@odata.context": "/redfish/v1/$metadata#HpeLogEntry.HpeLogEntry",
            "@odata.type": "#HpeLogEntry.v2_3_0.HpeLogEntry",
            "Categories": [
                "Administration"
            ],
            "Class": 32,
            "ClassDescription": "System Revision",
            "Code": 2,
            "Count": 1,
            "EventNumber": 190,
            "Severity": "Informational",
            "Updated": "2022-01-10T22:29:59Z"
        }
    },
    "OemRecordFormat": "Hpe-IML",
    "Severity": "OK"
}

=== Cray-HPE/csm-redfish-interface-emulator/mockups/DL325/Systems/1/LogServices/IML/Entries/91/index.json
{
    "@odata.context": "/redfish/v1/$metadata#LogEntry.LogEntry",
    "@odata.etag": "W/\"BB4C7BFD\"",
    "@odata.id": "/redfish/v1/Systems/1/LogServices/IML/Entries/91",
    "@odata.type": "#LogEntry.v1_1_0.LogEntry",
    "Id": "91",
    "Created": "2021-06-18T02:03:09Z",
    "EntryType": "Oem",
    "Message": "System Power Supply: Input Power Loss or Unplugged Power Cord, Verify Power Supply Input (Power Supply 1)",
    "Name": "Integrated Management Log",
    "Oem": {
        "Hpe": {
            "@odata.context": "/redfish/v1/$metadata#HpeLogEntry.HpeLogEntry",
            "@odata.type": "#HpeLogEntry.v2_3_0.HpeLogEntry",
            "Categories": [
                "Power"
            ],
            "Class": 11,
            "ClassDescription": "Power",
            "Code": 82,
            "Count": 1,
            "EventNumber": 300,
            "LearnMoreLink": "http://www.hpe.com/support/class0x000bcode0x0052-gen10",
            "RecommendedAction": "Check the power source, then test and replace any failed power supplies.",
            "Repaired": false,
            "Severity": "Caution",
            "Updated": "2021-06-18T02:03:09Z"
        }
    },
    "OemRecordFormat": "Hpe-IML",
    "Severity": "Warning"
}
